name: cli-plugin
description: Adds the capability of a CLI to the python-app-template
display-name: cli-plugin
picture: plugin.png
category: backend # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#category
compatibility:
  - java
  - spring
about: docs/about.md
usage: docs/usage.md
use-case: docs/use-case.md
implementation: docs/implementation.md
technologies: # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#technologies
  - "Api"
types:
  - app
inputs:
  - label: CLI Command Name
    type: text
    name: cli_command_name
    default: mycli
global-computed-inputs:
  cli_command_name_lower: "{{inputs.cli_command_name|lower}}"
hooks:
  - type: edit
    trigger: before-render
    path: "src/setup.py"
    changes:
      - search:
          string: ")"
          insert-before:
            snippet: snippets/entrypoints
          when:
            not-exists: "'console_scripts'"
      - search:
          string: "'pytest'"
          replace-by:
            value: "'pytest', 'click'"
          when:
            not-exists: "'click'"
      - search:
          string: "packages=['{{project_name_sanitized}}']"
          replace-by:
            value: "packages=['{{project_name_sanitized}}', '{{project_name_sanitized}}.commands', '{{project_name_sanitized}}.commands.say']"
          when:
            not-exists: "'{{project_name_sanitized}}.commands', '{{project_name_sanitized}}.commands.say'"
